name: 'mini_lakehouse'
version: '1.0.0'
profile: 'mini_lakehouse'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mini_lakehouse:
    +materialized: table
    staging:
      +schema: staging
    curated:
      +schema: curated

snapshots:
  mini_lakehouse: {}
